### ISSUE TITLE
Error running when installed through HACS

### ISSUE THREAD

**Issue by Phibins** [benleb/ad-ench#14]
When installed through HACS, and edited the config file as instructed I get the following error:

`2020-04-02 18:47:16.335239 INFO AppDaemon: Initializing app ench using class EnCh from module ench
2020-04-02 18:47:16.340476 WARNING AppDaemon: ------------------------------------------------------------
2020-04-02 18:47:16.340538 WARNING AppDaemon: Unexpected error initializing app: ench:
2020-04-02 18:47:16.340627 WARNING AppDaemon: ------------------------------------------------------------
2020-04-02 18:47:16.340954 WARNING AppDaemon: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/appdaemon.py", line 2051, in check_app_updates
    self.init_object(app)
  File "/usr/lib/python3.8/site-packages/appdaemon/appdaemon.py", line 1567, in init_object
    modname = __import__(app_args["module"])
  File "/config/appdaemon/apps/ad-ench/ench.py", line 31, in <module>
    import hassapi as hass
ModuleNotFoundError: No module named 'hassapi'
`

I changed line 31 from `import hassapi as hass` to `import appdaemon.plugins.hass.hassapi as hass`
 and it seems to resolve the issue

Im on hassio on docker (HA 0.107) and installed app-daemon through the add-on store.

**Comment by benleb** [comment]
Seems like an outdated version of appdaemon? :)

**Comment by Phibins** [comment]
Are you certain that's the issue? I have autoupdate enabled.

But maybe that is all it was.

Made the ticket for posterity so hopefully it helps someone.

**Comment by benleb** [comment]
Lets find out ;) Which AD versions are you running?

**Comment by Phibins** [comment]
5.0.1

But my autoupdate wasn't on, although I believe that I was up to date at the time of opening the ticket.

but I won't be able to test by reverting the code back until I'm back at my desk later this evening.
![Screenshot_20200506-090147](https://user-images.githubusercontent.com/37847843/81181865-0cfedc80-8f7b-11ea-8775-686e841409a9.png)

**Comment by benleb** [comment]
Ok, as expected... You are running AppDaemon version 3.x and the AppDaemon HassIO Plugin in version 5.0.1.

AppDaemon 3.x was deprecated some weeks or even month ago and you should update to a HassIO Plugin which uses AD 4 and not AD 3 :)

You probably can find further information about this in the repo/readme of the AD plugin developed by @frenck 👍
