### ISSUE TITLE
Python 3.7 is the minimum version supported

### ISSUE THREAD

**Issue by xaviml** [benleb/ad-ench#18]
Hi @benleb ,

First of all, thanks for this awesome project, I use it on my setup and it saved me hours of my life :)

I am raising this issue due to a [topic](https://community.home-assistant.io/t/need-help-getting-ench-to-work/197291) from the HA community. Due to the use of [await keyword inside f-strings](https://bugs.python.org/issue28942), this code is only compatible with Python >= 3.7. However, the minimum supported version of Python for AppDaemon is Python 3.6 (https://github.com/home-assistant/appdaemon/blob/e82bd7cd63e8f972315b4606f63d8e91227f4da5/setup.py#L29). This means that if someone runs your app on Python 3.6, it will crash (see topic from above).

I am not creating this issue so you make it compatible with Python 3.6 (like AppDaemon). I just wanted you to know this in case you were not aware of it and you are wiling to fix it.

Thanks :)

------------
The error logs that appear when running on Python 3.6:
```
2020-05-19 15:55:00.319878 INFO AppDaemon: Initializing app ench using class EnCh from module ench
2020-05-19 15:55:00.322201 WARNING AppDaemon: ------------------------------------------------------------
2020-05-19 15:55:00.322325 WARNING AppDaemon: Unexpected error initializing app: ench:
2020-05-19 15:55:00.322416 WARNING AppDaemon: ------------------------------------------------------------
2020-05-19 15:55:00.322669 WARNING AppDaemon: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 2051, in check_app_updates
    self.init_object(app)
  File "/usr/local/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 1567, in init_object
    modname = __import__(app_args["module"])
  File "<fstring>", line 1
    (await self._name(entity))
              ^
SyntaxError: invalid syntax
```

**Comment by benleb** [comment]
Thanks, its even 3.8 ;) And also documented in the readme now :)
