### ISSUE TITLE
AD3 compatibility issue / UnboundLocalError: local variable 'state'/'battery_level' referenced before assignment

### ISSUE THREAD

**Issue by CodeFinder2** [benleb/ad-ench#7]
Tried with beta v0.4.10, Log:
```
  Downloading https://files.pythonhosted.org/packages/d0/9e/7fdc6ae0dbcfff51ddc3a99c4ff5b23f564bb71a4b3676b1aad8f9372758/adutils-0.4.6-py3-none-any.whl
Installing collected packages: adutils
Successfully installed adutils-0.4.6
You are using pip version 19.0.3, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
[cont-init.d] appdaemon.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[12:04:46] INFO: Starting AppDaemon...
2020-01-04 12:04:47.405658 INFO AppDaemon Version 3.0.5 starting
2020-01-04 12:04:47.406264 INFO Configuration read from: /config/appdaemon/appdaemon.yaml
2020-01-04 12:04:47.409114 INFO AppDaemon: Starting Apps
2020-01-04 12:04:47.415818 INFO AppDaemon: Loading Plugin HASS using class HassPlugin from module hassplugin
2020-01-04 12:04:47.603501 INFO AppDaemon: HASS: HASS Plugin Initializing
2020-01-04 12:04:47.604327 INFO AppDaemon: HASS: HASS Plugin initialization complete
2020-01-04 12:04:47.604903 INFO Starting Dashboards
2020-01-04 12:04:47.617067 INFO API is disabled
2020-01-04 12:04:47.629191 INFO AppDaemon: HASS: Connected to Home Assistant 0.103.5
2020-01-04 12:04:47.782085 INFO AppDaemon: Got initial state from namespace default
2020-01-04 12:04:49.796236 INFO AppDaemon: Reading config
2020-01-04 12:04:49.818645 INFO AppDaemon: /config/appdaemon/apps/apps.yaml added or modified
2020-01-04 12:04:49.818927 INFO AppDaemon: /config/appdaemon/apps/apps.yaml added or modified
2020-01-04 12:04:49.819170 INFO AppDaemon: App 'hello_world' added
2020-01-04 12:04:49.819391 INFO AppDaemon: App 'ench' added
2020-01-04 12:04:49.819739 INFO AppDaemon: Adding /config/appdaemon/apps to module import path
2020-01-04 12:04:49.820103 INFO AppDaemon: Adding /config/appdaemon/apps/ench to module import path
2020-01-04 12:04:49.820473 INFO AppDaemon: Adding /config/appdaemon/apps/ench/adutils to module import path
2020-01-04 12:04:49.820884 INFO AppDaemon: Adding /config/appdaemon/apps/ench/adutils/.github to module import path
2020-01-04 12:04:49.821206 INFO AppDaemon: Adding /config/appdaemon/apps/ench/adutils/.github/workflows to module import path
2020-01-04 12:04:49.821530 INFO AppDaemon: Adding /config/appdaemon/apps/ench/adutils/adutils to module import path
2020-01-04 12:04:49.822731 INFO AppDaemon: Loading App Module: /config/appdaemon/apps/hello.py
2020-01-04 12:04:49.842128 INFO AppDaemon: Loading App Module: /config/appdaemon/apps/ench/ench.py
2020-01-04 12:04:49.851075 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/ench/adutils/setup.py - ignoring
2020-01-04 12:04:49.851418 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/ench/adutils/adutils/__init__.py - ignoring
2020-01-04 12:04:49.851760 INFO AppDaemon: Initializing app hello_world using class HelloWorld from module hello
2020-01-04 12:04:50.011367 INFO hello_world: Hello from AppDaemon
2020-01-04 12:04:50.014966 INFO hello_world: You are now ready to run Apps!
2020-01-04 12:04:50.015308 INFO AppDaemon: Initializing app ench using class EnCh from module ench
2020-01-04 12:04:50.020099 INFO ench:  
2020-01-04 12:04:50.023161 INFO ench:  EnCh
2020-01-04 12:04:50.026606 INFO ench:  
2020-01-04 12:04:50.029362 INFO ench:    notify: notify.mobile_app_oneplus_a3003
2020-01-04 12:04:50.032057 INFO ench:    show_friendly_name: False
2020-01-04 12:04:50.034778 INFO ench:    battery:
2020-01-04 12:04:50.037716 INFO ench:      interval_min: 1min
2020-01-04 12:04:50.040582 INFO ench:      min_level: 90%
2020-01-04 12:04:50.043320 INFO ench:    unavailable:
2020-01-04 12:04:50.046238 INFO ench:      interval_min: 60min
2020-01-04 12:04:50.048986 INFO ench:    exclude:
2020-01-04 12:04:50.051665 INFO ench:      - binary_sensor.updater
2020-01-04 12:04:50.054383 INFO ench:      - persistent_notification.config_entry_discovery
2020-01-04 12:04:50.056943 INFO ench:  
2020-01-04 12:04:50.059128 INFO ench:  
2020-01-04 12:04:50.061358 INFO ench:   Please convert your interval (in hours) setting to interval_min (in minutes)
2020-01-04 12:04:50.063552 INFO ench:   The interval option will be removed in  future release
2020-01-04 12:04:50.065778 INFO ench:  
2020-01-04 12:04:50.066893 INFO AppDaemon: App initialization complete
2020-01-04 12:06:50.019230 INFO ench:  Checking entities for low battery levels...
2020-01-04 12:06:50.052799 INFO ench:  Checking entities for unavailable/unknown state...
2020-01-04 12:06:50.175857 INFO ench:  Failed to get state for automation.badradio_ein_ausschalten: get_state() got multiple values for argument 'entity_id'
2020-01-04 12:06:50.181419 WARNING AppDaemon: ------------------------------------------------------------
2020-01-04 12:06:50.183067 WARNING AppDaemon: Unexpected error in worker for App ench:
2020-01-04 12:06:50.183393 WARNING AppDaemon: Worker Ags: {'name': 'ench', 'id': UUID('15e3382c-5a30-4722-8fb4-ada0a97a3cfb'), 'type': 'timer', 'function': <bound method EnCh.check_battery of <ench.EnCh object at 0xb4a31150>>, 'kwargs': {'interval': 60}}
2020-01-04 12:06:50.183645 WARNING AppDaemon: ------------------------------------------------------------
2020-01-04 12:06:50.184503 WARNING AppDaemon: Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/appdaemon/appdaemon.py", line 586, in worker
    funcref(self.sanitize_timer_kwargs(app, args["kwargs"]))
  File "/config/appdaemon/apps/ench/ench.py", line 147, in check_battery
    if battery_level and battery_level <= self.cfg["battery"]["min_level"]:
UnboundLocalError: local variable 'battery_level' referenced before assignment

2020-01-04 12:06:50.184818 WARNING AppDaemon: ------------------------------------------------------------
2020-01-04 12:06:50.197347 INFO ench:  Failed to get state for automation.badradio_ein_ausschalten: get_state() got multiple values for argument 'entity_id'
2020-01-04 12:06:50.200167 WARNING AppDaemon: ------------------------------------------------------------
2020-01-04 12:06:50.200728 WARNING AppDaemon: Unexpected error in worker for App ench:
2020-01-04 12:06:50.201242 WARNING AppDaemon: Worker Ags: {'name': 'ench', 'id': UUID('15e3382c-5a30-4722-8fb4-ada0a97a3cfb'), 'type': 'timer', 'function': <bound method EnCh.check_unavailable of <ench.EnCh object at 0xb4a31150>>, 'kwargs': {'interval': 3600}}
2020-01-04 12:06:50.201629 WARNING AppDaemon: ------------------------------------------------------------
2020-01-04 12:06:50.202519 WARNING AppDaemon: Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/appdaemon/appdaemon.py", line 586, in worker
    funcref(self.sanitize_timer_kwargs(app, args["kwargs"]))
  File "/config/appdaemon/apps/ench/ench.py", line 183, in check_unavailable
    if state in BAD_STATES and entity not in results:
UnboundLocalError: local variable 'state' referenced before assignment

2020-01-04 12:06:50.202964 WARNING AppDaemon: ------------------------------------------------------------
2020-01-04 12:07:50.027267 INFO ench:  Checking entities for low battery levels...
2020-01-04 12:07:50.080486 INFO ench:  Failed to get state for automation.badradio_ein_ausschalten: get_state() got multiple values for argument 'entity_id'
2020-01-04 12:07:50.081044 WARNING AppDaemon: ------------------------------------------------------------
2020-01-04 12:07:50.081336 WARNING AppDaemon: Unexpected error in worker for App ench:
2020-01-04 12:07:50.081607 WARNING AppDaemon: Worker Ags: {'name': 'ench', 'id': UUID('15e3382c-5a30-4722-8fb4-ada0a97a3cfb'), 'type': 'timer', 'function': <bound method EnCh.check_battery of <ench.EnCh object at 0xb4a31150>>, 'kwargs': {'interval': 60}}
2020-01-04 12:07:50.081878 WARNING AppDaemon: ------------------------------------------------------------
2020-01-04 12:07:50.082620 WARNING AppDaemon: Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/appdaemon/appdaemon.py", line 586, in worker
    funcref(self.sanitize_timer_kwargs(app, args["kwargs"]))
  File "/config/appdaemon/apps/ench/ench.py", line 147, in check_battery
    if battery_level and battery_level <= self.cfg["battery"]["min_level"]:
UnboundLocalError: local variable 'battery_level' referenced before assignment

2020-01-04 12:07:50.083085 WARNING AppDaemon: ------------------------------------------------------------
```

**Comment by benleb** [comment]
oh lol AD4 changed the name of the entity/entity_id attribute... https://github.com/benleb/ad-ench/commit/a7b0a3ec81803f3c58919318bcdba828eee339b4 should fix this, can you try? :)

And btw, the reasons I just want(ed) to support AD4 are listed here https://appdaemon.readthedocs.io/en/dev/HISTORY.html ;) But as they have release cycles like game consoles...^^

**Comment by CodeFinder2** [comment]
Thanks for clarifying! 😊

Here's the latest log for `master`:
```text
-----------------------------------------------------------
 Hass.io Add-on: AppDaemon
 Python Apps and HADashboard using AppDaemon 3.x for Home Assistant
-----------------------------------------------------------
 Add-on version: 4.1.0
 You are running the latest version of this add-on.
 System: Ubuntu 18.04.3 LTS  (armv7 / odroid-xu)
 Home Assistant version: 0.103.5
 Supervisor version: 193
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] appdaemon.sh: executing... 
[12:36:38] INFO: Updating Hass.io API token in AppDaemon with the current one...
Looking in links: https://wheels.hass.io/alpine-3.10/armv7/
Collecting adutils
  Downloading https://files.pythonhosted.org/packages/d0/9e/7fdc6ae0dbcfff51ddc3a99c4ff5b23f564bb71a4b3676b1aad8f9372758/adutils-0.4.6-py3-none-any.whl
Installing collected packages: adutils
Successfully installed adutils-0.4.6
You are using pip version 19.0.3, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
[cont-init.d] appdaemon.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[12:36:48] INFO: Starting AppDaemon...
2020-01-04 12:36:49.510679 INFO AppDaemon Version 3.0.5 starting
2020-01-04 12:36:49.511197 INFO Configuration read from: /config/appdaemon/appdaemon.yaml
2020-01-04 12:36:49.513963 INFO AppDaemon: Starting Apps
2020-01-04 12:36:49.521292 INFO AppDaemon: Loading Plugin HASS using class HassPlugin from module hassplugin
2020-01-04 12:36:49.744071 INFO AppDaemon: HASS: HASS Plugin Initializing
2020-01-04 12:36:49.745304 INFO AppDaemon: HASS: HASS Plugin initialization complete
2020-01-04 12:36:49.745992 INFO Starting Dashboards
2020-01-04 12:36:49.760652 INFO API is disabled
2020-01-04 12:36:49.772377 INFO AppDaemon: HASS: Connected to Home Assistant 0.103.5
2020-01-04 12:36:49.926176 INFO AppDaemon: Got initial state from namespace default
2020-01-04 12:36:51.945549 INFO AppDaemon: Reading config
2020-01-04 12:36:51.965574 INFO AppDaemon: /config/appdaemon/apps/apps.yaml added or modified
2020-01-04 12:36:51.965860 INFO AppDaemon: /config/appdaemon/apps/apps.yaml added or modified
2020-01-04 12:36:51.966093 INFO AppDaemon: App 'hello_world' added
2020-01-04 12:36:51.966311 INFO AppDaemon: App 'ench' added
2020-01-04 12:36:51.966648 INFO AppDaemon: Adding /config/appdaemon/apps to module import path
2020-01-04 12:36:51.967032 INFO AppDaemon: Adding /config/appdaemon/apps/ench to module import path
2020-01-04 12:36:51.967408 INFO AppDaemon: Adding /config/appdaemon/apps/ench/adutils to module import path
2020-01-04 12:36:51.967739 INFO AppDaemon: Adding /config/appdaemon/apps/ench/adutils/.github to module import path
2020-01-04 12:36:51.968057 INFO AppDaemon: Adding /config/appdaemon/apps/ench/adutils/.github/workflows to module import path
2020-01-04 12:36:51.968378 INFO AppDaemon: Adding /config/appdaemon/apps/ench/adutils/adutils to module import path
2020-01-04 12:36:51.969750 INFO AppDaemon: Loading App Module: /config/appdaemon/apps/hello.py
2020-01-04 12:36:51.992124 INFO AppDaemon: Loading App Module: /config/appdaemon/apps/ench/ench.py
2020-01-04 12:36:52.004180 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/ench/adutils/setup.py - ignoring
2020-01-04 12:36:52.004565 WARNING AppDaemon: No app description found for: /config/appdaemon/apps/ench/adutils/adutils/__init__.py - ignoring
2020-01-04 12:36:52.005041 INFO AppDaemon: Initializing app hello_world using class HelloWorld from module hello
2020-01-04 12:36:52.178584 INFO hello_world: Hello from AppDaemon
2020-01-04 12:36:52.181785 INFO hello_world: You are now ready to run Apps!
2020-01-04 12:36:52.182129 INFO AppDaemon: Initializing app ench using class EnCh from module ench
2020-01-04 12:36:52.186905 INFO ench:  
2020-01-04 12:36:52.189861 INFO ench:  EnCh
2020-01-04 12:36:52.193257 INFO ench:  
2020-01-04 12:36:52.196012 INFO ench:    notify: notify.mobile_app_oneplus_a3003
2020-01-04 12:36:52.198791 INFO ench:    show_friendly_name: False
2020-01-04 12:36:52.201589 INFO ench:    battery:
2020-01-04 12:36:52.204548 INFO ench:      interval_min: 1min
2020-01-04 12:36:52.207548 INFO ench:      min_level: 90%
2020-01-04 12:36:52.210315 INFO ench:    unavailable:
2020-01-04 12:36:52.213272 INFO ench:      interval_min: 60min
2020-01-04 12:36:52.216004 INFO ench:    exclude:
2020-01-04 12:36:52.218777 INFO ench:      - binary_sensor.updater
2020-01-04 12:36:52.221562 INFO ench:      - persistent_notification.config_entry_discovery
2020-01-04 12:36:52.224160 INFO ench:  
2020-01-04 12:36:52.226400 INFO ench:  
2020-01-04 12:36:52.228595 INFO ench:   Please convert your interval (in hours) setting to interval_min (in minutes)
2020-01-04 12:36:52.230852 INFO ench:   The interval option will be removed in  future release
2020-01-04 12:36:52.233106 INFO ench:  
2020-01-04 12:36:52.236270 INFO AppDaemon: App initialization complete
2020-01-04 12:38:52.018771 INFO ench:  Checking entities for unavailable/unknown state...
2020-01-04 12:38:52.036302 INFO ench:  Checking entities for low battery levels...
2020-01-04 12:38:52.192445 WARNING AppDaemon: ------------------------------------------------------------
2020-01-04 12:38:52.198486 WARNING AppDaemon: Unexpected error in worker for App ench:
2020-01-04 12:38:52.204230 WARNING AppDaemon: Worker Ags: {'name': 'ench', 'id': UUID('f9664bda-9d51-4aab-803c-fd6cba666565'), 'type': 'timer', 'function': <bound method EnCh.check_unavailable of <ench.EnCh object at 0xb63d8ff0>>, 'kwargs': {'interval': 3600}}
2020-01-04 12:38:52.204703 WARNING AppDaemon: ------------------------------------------------------------
2020-01-04 12:38:52.216258 WARNING AppDaemon: Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/appdaemon/appdaemon.py", line 586, in worker
    funcref(self.sanitize_timer_kwargs(app, args["kwargs"]))
  File "/config/appdaemon/apps/ench/ench.py", line 197, in check_unavailable
    f"{self._name(entity)} is {adu.hl(state)} | "
  File "/config/appdaemon/apps/ench/ench.py", line 232, in last_update
    lu_date, lu_time = self._to_localtime(entity, "last_updated")
  File "/config/appdaemon/apps/ench/ench.py", line 246, in _to_localtime
    timedelta(minutes=self.get_tz_offset()), name=self.get_timezone()
AttributeError: 'EnCh' object has no attribute 'get_timezone'

2020-01-04 12:38:52.216611 WARNING AppDaemon: ------------------------------------------------------------
2020-01-04 12:38:52.246830 INFO ench:  no entities with low battery levels found
2020-01-04 12:39:52.011252 INFO ench:  Checking entities for low battery levels...
2020-01-04 12:39:52.103964 INFO ench:  no entities with low battery levels found
```

**Comment by benleb** [comment]
fixed in https://github.com/benleb/ad-ench/commit/58e54ba08bd2912fb8a085a1e092c1d4c9d3d0de

**Comment by CodeFinder2** [comment]
Guess we are making progress here 😁

Starts just fine, reports unavailable entities (apparently) correctly but it is not detecting low battery entities at all. My threshold is 90% so there should be many of them...

**Comment by CodeFinder2** [comment]
Okay, wait: I just received a battery notification about my mobile phone (90%). :laughing: 

But there are many more sensors in my network having a battery level <= 90%. My phone now receives one notification per minute but with only one sensor (the phone itself).

For instance, `sensor.0x00158d0002d80e46_battery` reports `57`. New log:
```text
2020-01-04 13:25:26.018483 INFO ench:  Checking entities for low battery levels...
2020-01-04 13:25:26.046576 INFO ench:  Checking entities for unavailable/unknown state...
2020-01-04 13:25:26.180165 INFO ench:  no entities with low battery levels found
2020-01-04 13:25:26.181443 INFO ench:  climate.0x00158d000192d207_climate is unknown | last update: 2019-12-31T15:09:13.679667+00:00
2020-01-04 13:25:26.183540 INFO ench:  climate.0x00158d0001ff9112_climate is unknown | last update: 2019-12-31T15:09:13.689440+00:00
2020-01-04 13:25:26.189101 INFO ench:  group.all_vacuum_cleaners is unknown | last update: 2019-12-31T12:53:50.908043+00:00
2020-01-04 13:25:26.193444 INFO ench:  person.adrian_bockenkamp is unknown | last update: 2019-12-31T12:53:51.706690+00:00
2020-01-04 13:25:26.198154 INFO ench:  sensor.0x00158d000192d207_battery is unknown | last update: 2019-12-31T15:09:13.587010+00:00
2020-01-04 13:25:26.200075 INFO ench:  sensor.0x00158d000192d207_linkquality is unknown | last update: 2019-12-31T15:09:13.585603+00:00
2020-01-04 13:25:26.202071 INFO ench:  sensor.0x00158d0001ff9112_battery is unknown | last update: 2019-12-31T15:09:13.636472+00:00
2020-01-04 13:25:26.204042 INFO ench:  sensor.0x00158d0001ff9112_linkquality is unknown | last update: 2019-12-31T15:09:13.638356+00:00
2020-01-04 13:25:26.844875 INFO ench:  8 entities with unavailable/unknown state!
2020-01-04 13:26:26.015302 INFO ench:  Checking entities for low battery levels...
2020-01-04 13:26:26.079100 INFO ench:  device_tracker.oneplus_a3003 has low battery ��� 90% | last update: 2020-01-04T12:25:38.624694+00:00
2020-01-04 13:26:26.708249 INFO ench:  1 entities with low battery levels!
2020-01-04 13:27:26.015512 INFO ench:  Checking entities for low battery levels...
2020-01-04 13:27:26.078104 INFO ench:  device_tracker.oneplus_a3003 has low battery ��� 90% | last update: 2020-01-04T12:25:38.624694+00:00
2020-01-04 13:27:26.808263 INFO ench:  1 entities with low battery levels!
2020-01-04 13:28:26.017284 INFO ench:  Checking entities for low battery levels...
2020-01-04 13:28:26.132349 INFO ench:  device_tracker.oneplus_a3003 has low battery ��� 90% | last update: 2020-01-04T12:25:38.624694+00:00
2020-01-04 13:28:26.759551 INFO ench:  1 entities with low battery levels!
2020-01-04 13:29:26.018806 INFO ench:  Checking entities for low battery levels...
2020-01-04 13:29:26.082099 INFO ench:  device_tracker.oneplus_a3003 has low battery ��� 90% | last update: 2020-01-04T12:25:38.624694+00:00
2020-01-04 13:29:26.745683 INFO ench:  1 entities with low battery levels!
```

**Comment by benleb** [comment]
wow is your interval set to a really low value?! or is this another thing?

hm interesting is that this works in my ad3 docker container. It would be interesting to see what values it gets, can you put this line
`self.adu.log(f"{entity} battery_level: {battery_level}%")`
at this place
![image](https://user-images.githubusercontent.com/512997/71765533-718b2b80-2ef6-11ea-84ce-38987900af5c.png)
to check?

if used in my ad3 container it works:
![image](https://user-images.githubusercontent.com/512997/71765582-fd04bc80-2ef6-11ea-964b-256c88343c57.png)

**Comment by benleb** [comment]
no the battery_level is the name of the default attribute for all entities which have a battery level. your names or friendly names don't matter

**Comment by CodeFinder2** [comment]
Yeah I am using an `internal_min` of 1 (minute) ... just to speedup our testing here. :smiley: 

Will now test what happens with adding that LOC ...

Ah, okay thanks for letting me know. I was searching through my HA's entity registry for `battery_level`, found nothing and was kinda confused.

Note that I've excluded nothing yet, this is my complete AD config `apps.yaml`:
```yaml
# This file specifies what apps to load in AppDaemon as well as their configuration and dependencies (between apps).
# Please note that system/python package dependencies must be added to the AppDaemon HassIO addon configuration in the web UI of the AppDaemon addon.

---
hello_world:
  module: hello
  class: HelloWorld

# Entity checker: periodically check for devices with low battery or that are unavailable:
ench:
  module: ench
  class: EnCh
  notify: "notify.mobile_app_oneplus_a3003"
  show_friendly_name: False
  battery:
    interval: 45
    interval_min: 1
    min_level: 90
  unavailable:
    interval_min: 60
#  exclude:
#    - sensor.out_of_order
#    - binary_sensor.always_unavailable
```

**Comment by benleb** [comment]
ah okay, thats a whole new bug. I just check the `battery_level` attribute, if not present - no battery check. But seems there are some devices which do not follow this structure and create an own battery sensor or the attribute is called `Battery Level`

So, would you agree that the AD3 bugs are solved? Then we can close this and discuss to include the other ways some devices use to report their level

**Comment by CodeFinder2** [comment]
> [...] hm interesting is that this works in my ad3 docker container. It would be interesting to see what values it gets, can you put this line
> `self.adu.log(f"{entity} battery_level: {battery_level}%")`
> at this place
> ![image](https://user-images.githubusercontent.com/512997/71765533-718b2b80-2ef6-11ea-84ce-38987900af5c.png)
> to check? [...]

Just did that: of course I get a lot of output but what's interesting for example, is this (snippet):
```text
2020-01-04 13:44:11.647633 INFO ench:  sensor.grunlilie_battery battery_level: None%
2020-01-04 13:44:11.649662 INFO ench:  sensor.grunlilie_conductivity battery_level: None%
2020-01-04 13:44:11.651524 INFO ench:  sensor.grunlilie_light_intensity battery_level: None%
2020-01-04 13:44:11.653408 INFO ench:  sensor.grunlilie_moisture battery_level: None%
2020-01-04 13:44:11.655231 INFO ench:  sensor.grunlilie_temperature battery_level: None%
2020-01-04 13:44:11.657147 INFO ench:  sensor.hacs battery_level: None%
2020-01-04 13:44:11.659005 INFO ench:  sensor.installed_hassio_version battery_level: None%
2020-01-04 13:44:11.661093 INFO ench:  sensor.kentia_palme_battery battery_level: None%
2020-01-04 13:44:11.662966 INFO ench:  sensor.kentia_palme_conductivity battery_level: None%
2020-01-04 13:44:11.664855 INFO ench:  sensor.kentia_palme_light_intensity battery_level: None%
2020-01-04 13:44:11.666688 INFO ench:  sensor.kentia_palme_moisture battery_level: None%
2020-01-04 13:44:11.668549 INFO ench:  sensor.kentia_palme_temperature battery_level: None%
[...]
2020-01-04 13:44:11.786221 INFO ench:  timer.zigbee_permit_join battery_level: None%
2020-01-04 13:44:11.788006 INFO ench:  vacuum.rockrobo battery_level: 100%
2020-01-04 13:44:11.789849 INFO ench:  vacuum.servus battery_level: 100%
2020-01-04 13:44:11.791622 INFO ench:  weather.home battery_level: None%
2020-01-04 13:44:11.793439 INFO ench:  weather.wetter battery_level: None%
2020-01-04 13:44:11.795215 INFO ench:  zigbee2mqtt_networkmap.map_last_update battery_level: None%
2020-01-04 13:44:11.797029 INFO ench:  zone.arbeit battery_level: None%
2020-01-04 13:44:11.798807 INFO ench:  zone.home battery_level: None%
2020-01-04 13:44:11.844002 INFO ench:  8 entities with unavailable/unknown state!
2020-01-04 13:44:12.485672 INFO ench:  1 entities with low battery levels!
```

Actually, `sensor.kentia_palme_battery` has a battery level of 82.

**Comment by CodeFinder2** [comment]
Okay, closing this to continue in #8.
